name: Build ðŸ”§ the Jupyter Book ðŸ“– and deploy ðŸš€ it to GitHub Pages
on: push
jobs:
  build-n-deploy:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code ðŸ›Žï¸
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - name: Set up Python 3.7 ðŸ
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies ðŸ’¾
      run: pip install -r requirements.txt
    - name: Build the book ðŸ”§ðŸ“–
      run: jb build -nW .
    - name: Validate links â˜‘ï¸ðŸ”—
      continue-on-error: true
      run: jb build -q --builder linkcheck .
    - name: Deploy ðŸš€
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _build/html
        CLEAN: true
    - name: Deploy Too CNAME ðŸš€
      if: github.ref == 'refs/heads/pf-release'
      run: echo "too.simply-logical.space" > _build/html/CNAME
    - name: Deploy Too ðŸš€
      if: github.ref == 'refs/heads/pf-release'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.TOO }}
        REPOSITORY_NAME: simply-logical/simply-logical-too
        BRANCH: master
        FOLDER: _build/html
        CLEAN: true
